# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import study_room_pb2 as study__room__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in study_room_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoomServiceStub(object):
    """=============================================
    ROOM SERVICE - Manajemen data ruangan
    =============================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAllRooms = channel.unary_unary(
                '/studyroom.RoomService/GetAllRooms',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=study__room__pb2.RoomListResponse.FromString,
                _registered_method=True)
        self.GetRoomDetail = channel.unary_unary(
                '/studyroom.RoomService/GetRoomDetail',
                request_serializer=study__room__pb2.RoomRequest.SerializeToString,
                response_deserializer=study__room__pb2.RoomDetailResponse.FromString,
                _registered_method=True)
        self.WatchRoomAvailability = channel.unary_stream(
                '/studyroom.RoomService/WatchRoomAvailability',
                request_serializer=study__room__pb2.WatchRequest.SerializeToString,
                response_deserializer=study__room__pb2.RoomStatusUpdate.FromString,
                _registered_method=True)


class RoomServiceServicer(object):
    """=============================================
    ROOM SERVICE - Manajemen data ruangan
    =============================================
    """

    def GetAllRooms(self, request, context):
        """Unary: Ambil semua ruangan
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRoomDetail(self, request, context):
        """Unary: Ambil detail satu ruangan
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchRoomAvailability(self, request, context):
        """Server-side Streaming: Live update ketersediaan ruangan
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoomServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAllRooms': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllRooms,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=study__room__pb2.RoomListResponse.SerializeToString,
            ),
            'GetRoomDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoomDetail,
                    request_deserializer=study__room__pb2.RoomRequest.FromString,
                    response_serializer=study__room__pb2.RoomDetailResponse.SerializeToString,
            ),
            'WatchRoomAvailability': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchRoomAvailability,
                    request_deserializer=study__room__pb2.WatchRequest.FromString,
                    response_serializer=study__room__pb2.RoomStatusUpdate.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'studyroom.RoomService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('studyroom.RoomService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RoomService(object):
    """=============================================
    ROOM SERVICE - Manajemen data ruangan
    =============================================
    """

    @staticmethod
    def GetAllRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/studyroom.RoomService/GetAllRooms',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            study__room__pb2.RoomListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRoomDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/studyroom.RoomService/GetRoomDetail',
            study__room__pb2.RoomRequest.SerializeToString,
            study__room__pb2.RoomDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchRoomAvailability(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/studyroom.RoomService/WatchRoomAvailability',
            study__room__pb2.WatchRequest.SerializeToString,
            study__room__pb2.RoomStatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BookingServiceStub(object):
    """=============================================
    BOOKING SERVICE - Pemesanan ruangan
    =============================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BookRoom = channel.unary_unary(
                '/studyroom.BookingService/BookRoom',
                request_serializer=study__room__pb2.BookingRequest.SerializeToString,
                response_deserializer=study__room__pb2.BookingResponse.FromString,
                _registered_method=True)
        self.CancelBooking = channel.unary_unary(
                '/studyroom.BookingService/CancelBooking',
                request_serializer=study__room__pb2.CancelRequest.SerializeToString,
                response_deserializer=study__room__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.GetBookingStatus = channel.unary_unary(
                '/studyroom.BookingService/GetBookingStatus',
                request_serializer=study__room__pb2.BookingStatusRequest.SerializeToString,
                response_deserializer=study__room__pb2.BookingStatusResponse.FromString,
                _registered_method=True)
        self.GetUserBookings = channel.unary_unary(
                '/studyroom.BookingService/GetUserBookings',
                request_serializer=study__room__pb2.UserRequest.SerializeToString,
                response_deserializer=study__room__pb2.UserBookingsResponse.FromString,
                _registered_method=True)


class BookingServiceServicer(object):
    """=============================================
    BOOKING SERVICE - Pemesanan ruangan
    =============================================
    """

    def BookRoom(self, request, context):
        """Unary: Booking sebuah ruangan
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelBooking(self, request, context):
        """Unary: Batalkan booking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBookingStatus(self, request, context):
        """Unary: Cek status booking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserBookings(self, request, context):
        """Unary: Lihat daftar booking aktif user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BookingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BookRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.BookRoom,
                    request_deserializer=study__room__pb2.BookingRequest.FromString,
                    response_serializer=study__room__pb2.BookingResponse.SerializeToString,
            ),
            'CancelBooking': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelBooking,
                    request_deserializer=study__room__pb2.CancelRequest.FromString,
                    response_serializer=study__room__pb2.CancelResponse.SerializeToString,
            ),
            'GetBookingStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBookingStatus,
                    request_deserializer=study__room__pb2.BookingStatusRequest.FromString,
                    response_serializer=study__room__pb2.BookingStatusResponse.SerializeToString,
            ),
            'GetUserBookings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserBookings,
                    request_deserializer=study__room__pb2.UserRequest.FromString,
                    response_serializer=study__room__pb2.UserBookingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'studyroom.BookingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('studyroom.BookingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BookingService(object):
    """=============================================
    BOOKING SERVICE - Pemesanan ruangan
    =============================================
    """

    @staticmethod
    def BookRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/studyroom.BookingService/BookRoom',
            study__room__pb2.BookingRequest.SerializeToString,
            study__room__pb2.BookingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelBooking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/studyroom.BookingService/CancelBooking',
            study__room__pb2.CancelRequest.SerializeToString,
            study__room__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBookingStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/studyroom.BookingService/GetBookingStatus',
            study__room__pb2.BookingStatusRequest.SerializeToString,
            study__room__pb2.BookingStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserBookings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/studyroom.BookingService/GetUserBookings',
            study__room__pb2.UserRequest.SerializeToString,
            study__room__pb2.UserBookingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class NotificationServiceStub(object):
    """=============================================
    NOTIFICATION SERVICE - Notifikasi real-time
    =============================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubscribeNotifications = channel.unary_stream(
                '/studyroom.NotificationService/SubscribeNotifications',
                request_serializer=study__room__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=study__room__pb2.Notification.FromString,
                _registered_method=True)
        self.SendNotification = channel.unary_unary(
                '/studyroom.NotificationService/SendNotification',
                request_serializer=study__room__pb2.SendNotifRequest.SerializeToString,
                response_deserializer=study__room__pb2.SendNotifResponse.FromString,
                _registered_method=True)
        self.GetNotificationHistory = channel.unary_unary(
                '/studyroom.NotificationService/GetNotificationHistory',
                request_serializer=study__room__pb2.UserRequest.SerializeToString,
                response_deserializer=study__room__pb2.NotificationHistoryResponse.FromString,
                _registered_method=True)


class NotificationServiceServicer(object):
    """=============================================
    NOTIFICATION SERVICE - Notifikasi real-time
    =============================================
    """

    def SubscribeNotifications(self, request, context):
        """Server-side Streaming: Terima notifikasi real-time
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendNotification(self, request, context):
        """Unary: Kirim notifikasi manual (admin)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNotificationHistory(self, request, context):
        """Unary: Ambil history notifikasi user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubscribeNotifications': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeNotifications,
                    request_deserializer=study__room__pb2.SubscribeRequest.FromString,
                    response_serializer=study__room__pb2.Notification.SerializeToString,
            ),
            'SendNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.SendNotification,
                    request_deserializer=study__room__pb2.SendNotifRequest.FromString,
                    response_serializer=study__room__pb2.SendNotifResponse.SerializeToString,
            ),
            'GetNotificationHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNotificationHistory,
                    request_deserializer=study__room__pb2.UserRequest.FromString,
                    response_serializer=study__room__pb2.NotificationHistoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'studyroom.NotificationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('studyroom.NotificationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NotificationService(object):
    """=============================================
    NOTIFICATION SERVICE - Notifikasi real-time
    =============================================
    """

    @staticmethod
    def SubscribeNotifications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/studyroom.NotificationService/SubscribeNotifications',
            study__room__pb2.SubscribeRequest.SerializeToString,
            study__room__pb2.Notification.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/studyroom.NotificationService/SendNotification',
            study__room__pb2.SendNotifRequest.SerializeToString,
            study__room__pb2.SendNotifResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNotificationHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/studyroom.NotificationService/GetNotificationHistory',
            study__room__pb2.UserRequest.SerializeToString,
            study__room__pb2.NotificationHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
